### PR TITLE
Install StereoKitCTest by default in CMake

### PR DESCRIPTION
**Pull request by slitcch**

### CODE REVIEW

**Comment by maluoi** [comment]
Not certain here, should this be gated by `SK_BUILD_TESTS`, or does that get handled properly automatically when the `StereoKitCTest` target doesn't exist?

**Comment by slitcch** [comment]
Oh hmm, let me try that.

**Comment by maluoi** [comment]
I imagine there may also be some work related to the Assets the app uses, the cmake file doesn't actually mention those anywhere.

**Comment by slitcch** [comment]
Yep, good catch :)

**Comment by slitcch** [comment]
Not high enough priority for me to bikeshed people on this, it's fine the way it was

**Pull request closed without merging**
