### PR TITLE
fix: msvc multi-configuration generator debug builds

### PR DESCRIPTION
**Pull request by austinbhale**
Hey Nick, when working with the MSVC generator, I don't need to set the `CMAKE_BUILD_TYPE` variable since it's not used by MSVC. Instead, I specify the `--config` option so that the build for that architecture can remain in a single VS project. These two small changes got it working: (1) avoid forcing a Release build of StereoKit for Debug builds (2) avoid copying the .pdb files if they don't exist, which was happening on Release builds. I'm also very open to changing how this might be done. Thanks!

### CODE REVIEW

**Comment by maluoi** [comment]
Debug info should exist for release builds! I did some work to ensure that would happen. If it's _not_ getting created, I may want to investigate why that's happening!

What's the core issue you're running into here, and what's your cmake command look like?

Also, don't mind the Linux failure, that one's on me. I really should not be directly committing to /develop anymore 😬

**Comment by austinbhale** [comment]
Nothing out of the ordinary just MSVC breaking linux 😆 This actually works well for the UWP ARM/x64 builds, however the Win32 x64 builds is where I can't reference a Debug configuration of StereoKit. Here are the Powershell portions to get the idea:

```
if ($plat -eq 'UWP') {
   & $cmakeCmd -G $vsGeneratorName -A $vsArch "-DPROJECT_GUID=$guid" '-DCMAKE_CXX_FLAGS=/MP' '-DCMAKE_SYSTEM_NAME=WindowsStore' '-DCMAKE_SYSTEM_VERSION=10.0' '-DDYNAMIC_LOADER=OFF' '-Wno-deprecated' '-Wno-dev' $PSScriptRoot
} else {
   & $cmakeCmd -G $vsGeneratorName -A $vsArch "-DPROJECT_GUID=$guid" '-DCMAKE_CXX_FLAGS=/MP' '-DDYNAMIC_LOADER=OFF' '-Wno-deprecated' '-Wno-dev' $PSScriptRoot
}

Write-Host "Building $arch $plat Debug" -ForegroundColor green
& $cmakeCmd --build . -j8 --config Debug -- /m
if ($LASTEXITCODE -ne 0) {
   Write-Host "--- Build failed! Stopping build! ---" -ForegroundColor red
   exit 1
}

Write-Host "Building $arch $plat Release" -ForegroundColor green
& $cmakeCmd --build . -j8 --config Release -- /m
if ($LASTEXITCODE -ne 0) {
   Write-Host "--- Build failed! Stopping build! ---" -ForegroundColor red
   exit 1
}
```

So if I manually specify `cmake --build . --config Debug` for the x64 Win32 project, I get:
```
MSBuild version 17.6.0-preview-23122-03+f93b24b5a for .NET Framework
cl : command line  error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64
_Win32\_deps\openxr_loader-build\src\loader\openxr_loader.vcxproj]
cl : command line  error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64
_Win32\_deps\reactphysics3d-build\reactphysics3d.vcxproj]
```

Release works as expected though

**Comment by maluoi** [comment]
The '/O2' and '/RTC1' errors look familiar, I may have had to do something to fix that on Release as well? I may not have actually tested cmake for Windows in debug mode yet, I've mostly been using that for the release path so far. Will definitely try that out here shortly!

**Comment by austinbhale** [comment]
You disable the /RTC1 flag but I don't think /O2 should be enabled for debug builds, which is happening since `CMAKE_BUILD_TYPE` is being forced as Release and going down that path?

**Comment by maluoi** [comment]
Oof, yeah I see what's going on here now 😩 That's exciting! I'll play around with this some.

Apparently I've just been providing the DEBUG/RELEASE flags for configure as well as on build, even for MSVC. An easy fix for now might be to do the same. I've also got [a cmake presets file](https://github.com/StereoKit/StereoKit/blob/develop/CMakePresets.json), dunno if that's helpful for you in this case, but right now I do all my builds using that: `cmake --workflow --preset Win32x64Release`.

**Comment by austinbhale** [comment]
Thanks sm for taking a look into it!

Do you get this error when configuring it a second time? If that worked, I might be able to reconfigure cmake twice and build for Debug/Release with '-DCMAKE_BUILD_TYPE' set differently since it'd overwrite the settings

```
MSBuild version 17.6.0-preview-23122-03+f93b24b5a for .NET Framework

  Checking Build System
  Performing update step for 'reactphysics3d-populate'
  Building Custom Rule C:/Users/Austin/Github/Nakamir/Nakamir/NakamirC/build/x64_Win32/_deps/reactphysics3d-subbuild/CMakeLists.txt
  Performing patch step for 'reactphysics3d-populate'
CUSTOMBUILD : error : patch failed: include/reactphysics3d/containers/Deque.h:114 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : include/reactphysics3d/containers/Deque.h: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: include/reactphysics3d/engine/Material.h:153 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : include/reactphysics3d/engine/Material.h: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: include/reactphysics3d/engine/PhysicsCommon.h:260 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : include/reactphysics3d/engine/PhysicsCommon.h: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: include/reactphysics3d/engine/PhysicsWorld.h:140 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : include/reactphysics3d/engine/PhysicsWorld.h: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: include/reactphysics3d/utils/DefaultLogger.h:98 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : include/reactphysics3d/utils/DefaultLogger.h: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: src/collision/shapes/ConcaveMeshShape.cpp:283 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : src/collision/shapes/ConcaveMeshShape.cpp: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: src/collision/shapes/ConvexMeshShape.cpp:205 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : src/collision/shapes/ConvexMeshShape.cpp: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: src/collision/shapes/HeightFieldShape.cpp:444 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : src/collision/shapes/HeightFieldShape.cpp: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: src/engine/PhysicsWorld.cpp:79 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : src/engine/PhysicsWorld.cpp: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : patch failed: src/systems/CollisionDetectionSystem.cpp:499 [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
CUSTOMBUILD : error : src/systems/CollisionDetectionSystem.cpp: patch does not apply [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build for 'C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-update.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-patch.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-configure.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-build.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-install.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\f4d31d67f4c5dfb9a0709b928eecd114\reactphysics3d-populate-test.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\46033822ea49b6b42b5aab5b87bc902a\reactphysics3d-populate-complete.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeFiles\5a35a67bb7dd010eb637b2b2186a13a5\reactphysics3d-populate.rule;C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\CMakeLists.txt' exited with code 1. [C:\Users\Austin\Github\Nakamir\Nakamir\NakamirC\build\x64_Win32\_deps\reactphysics3d-subbuild\reactphysics3d-populate.vcxproj]

CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1622 (message):
  Build step for reactphysics3d failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1762:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1762 (cmake_language)
  Nakamir/NakamirC/build/x64_Win32/cmake/CPM_0.32.2.cmake:762 (FetchContent_Populate)
  Nakamir/NakamirC/build/x64_Win32/cmake/CPM_0.32.2.cmake:590 (cpm_fetch_package)
  StereoKit/CMakeLists.txt:176 (CPMAddPackage)


--- Config failed! Stopping build! ---
```

**Comment by maluoi** [comment]
I've found some generator options that look promising for doing release/debug stuff with msvc! I may have a fix for that before long :)

The patch issue though... I've seen that pop up now and again recently, but I haven't figured out what exactly the conditions are that cause it! I also have no idea why it would fail some times and not others either. Might be something related to caching?

**Comment by maluoi** [comment]
Okay, I've added some stuff with #661 that should enable the more MSVC idiomatic configuration for Debug/Release.

I'll be looking into the physics patch thing next, but I might not get to that until tomorrow..? My current guess is that it's something to do with how git patches work with CPM (used for fetching and caching repos in cmake). Both my Windows machine and GitHub Actions are using a CPM cache folder, and I'm getting successful builds there. But I recently wiped my Linux distro, so no CPM cache there, and it's failing on that. We'll see!

**Comment by austinbhale** [comment]
You are the man!! I tried to repro the patch error too and these changes seemed to fix that! Thanks for prioritizing this - you expedited my build times :) Before I had to delete build folders to get it to cache properly. Best of luck getting the CPM cache folder resolved on linux, I'd try to help out if I were building more frequently there but not just yet

**Pull request closed without merging**
